import { Noto_Sans, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "@/components/tanstack_provider/TanstackProvider";
import { DarkModeProvider } from "@/darkmodecontext/DarkModeProvider";
import { Toaster } from "react-hot-toast";
import { DashboardContextProvider } from "@/dashboardcontext/DashboardContextProvider";
import { OrderFilterProvider } from "./Context/OrderContext/OrderContextProvider";
import { CartProvider } from "./Context/CartContext/CartContext";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  variable: "--font-nunitoSans",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-notoSans",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${nunitoSans.variable} ${notoSans.variable} font-sans text-gray-800`}
      >
        <DashboardContextProvider>
          <DarkModeProvider>
            <TanstackProvider>
              <OrderFilterProvider>
                <CartProvider>{children}</CartProvider>
              </OrderFilterProvider>
            </TanstackProvider>
          </DarkModeProvider>
        </DashboardContextProvider>
        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: "8px" }}
          toastOptions={{
            success: {
              duration: 3000,
            },
            error: {
              duration: 5000,
            },
            style: {
              fontSize: '16px',
              maxWidth: '600px',
              padding: '16px 24px',
              // backgroundColor: "bg-slate",
              // color: "var(--color-gray-700)",
            },
          }}
        />
      </body>
    </html>
  );
}
